### ISSUE TITLE
Add commitizen to pre-commit

### ISSUE THREAD

**Issue by imjoseangel** [imjoseangel/powerline-k8sstatus#13]
# SUMMARY

Add commitizen to pre-commit

## ISSUE TYPE

- Repository Maintenance

## COMPONENT NAME

pre-commit

## ADDITIONAL INFORMATION

```yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
```
