### ISSUE TITLE
Create release with workflow dispatch

### ISSUE THREAD

**Issue by imjoseangel** [imjoseangel/powerline-k8sstatus#28]
# SUMMARY

Analyze the best way to create a release with `workflow_dispatch`

## ISSUE TYPE

- Feature Idea

## COMPONENT NAME

Continuous Release

## ADDITIONAL INFORMATION

```yaml
name: Release and Deploy
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.cversion.outputs.version }}
          release_name: Release v${{ steps.cversion.outputs.version }}
          body: |
            # Ansible Collection: imjoseangel.common
            ![ReleaseBuildCollection](https://github.com/imjoseangel/ansiblecommon/workflows/ReleaseBuildCollection/badge.svg)
            Install with:
            ```sh
            ansible-galaxy collection install -r requirements.yml -f
            ```
            The requirements.yml needs to have the following format and content:
            ```yaml
            ---
            collections:
                - https://github.com/imjoseangel/ansiblecommon/releases/download/v${{ steps.cversion.outputs.version }}/imjoseangel-common-${{ steps.cversion.outputs.version }}.tar.gz
            ```
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: imjoseangel-common-${{ steps.cversion.outputs.version }}.tar.gz
          asset_name: imjoseangel-common-${{ steps.cversion.outputs.version }}.tar.gz
          asset_content_type: application/tar+gzip

```

<!--- HINT: You can also paste gist.github.com links for larger files -->
