### ISSUE TITLE
Fix Coverage Range

### ISSUE THREAD

**Issue by imjoseangel** [imjoseangel/powerline-k8sstatus#49]
# SUMMARY

Coverage is too strict with tests. We need to move to a range of 90

## ISSUE TYPE

- Issue Report

## VERSION

```paste below
21.2.2
```

## CONFIGURATION

```yaml
coverage:
  precision: 2
  round: down
  range: "90..100"
```

## OS / ENVIRONMENT

CI

## STEPS TO REPRODUCE

On every CI, Coverage is too strict

## EXPECTED RESULTS

Pass on 90%

## ACTUAL RESULTS

Tests not passing when over 90%
