### ISSUE TITLE
Include matrix Kubernetes on Tests

### ISSUE THREAD

**Issue by imjoseangel** [imjoseangel/powerline-k8sstatus#52]
# SUMMARY

## ISSUE TYPE

- Project Maintenance

## COMPONENT NAME

QA and CI

## ADDITIONAL INFORMATION

Test the following and change for K3S:

```yaml
      matrix:
        kubernetes:
          - "1.20"
          - "1.21"
          - "1.22"
```
